@baseUrl = http://localhost:3000/api

GET {{baseUrl}}/orders
Cookie: refresh_token=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiIwMGIwNWQwNC03MjA5LTQxMGUtYmIyZC0zODQwNWU0MGRkNzUiLCJpYXQiOjE3ODg0MjA5MzksImV4cCI6MTc4OTAyNTczOX0.ypMC4ei91Xu6Y_jSliPGtNkzqRP92K4rSAZHuWN7TfM;access_token=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiIwMGIwNWQwNC03MjA5LTQxMGUtYmIyZC0zODQwNWU0MGRkNzUiLCJpYXQiOjE3ODg0MjA5MzksImV4cCI6MTc4ODQyMTgzOX0.w9YmVOJMQp8Gb-PlI6cH3_wW2zVXAT_T-SLmASOyGvc;

###
GET {{baseUrl}}/orders/6145464f-d797-46d0-aa30-7a5a0c016e2f
Cookie: refresh_token=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiIwMGIwNWQwNC03MjA5LTQxMGUtYmIyZC0zODQwNWU0MGRkNzUiLCJpYXQiOjE3ODg0MjA5MzksImV4cCI6MTc4OTAyNTczOX0.ypMC4ei91Xu6Y_jSliPGtNkzqRP92K4rSAZHuWN7TfM;access_token=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiIwMGIwNWQwNC03MjA5LTQxMGUtYmIyZC0zODQwNWU0MGRkNzUiLCJpYXQiOjE3ODg0MjA5MzksImV4cCI6MTc4ODQyMTgzOX0.w9YmVOJMQp8Gb-PlI6cH3_wW2zVXAT_T-SLmASOyGvc;