@baseUrl = http://localhost:3000/api

GET {{baseUrl}}/orders
Cookie: refresh_token=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiIyZjg1ZDI4MC01MjY0LTQ2ZDktOWI2ZS01MjY1YjY5NDY4ZjAiLCJpYXQiOjE3ODc5NTUwMDksImV4cCI6MTc4ODU1OTgwOX0.pB1hAvHiK5qZlwzDzfDjH8o-p25KzoXuvjsQiMvOPN0;access_token=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiIyZjg1ZDI4MC01MjY0LTQ2ZDktOWI2ZS01MjY1YjY5NDY4ZjAiLCJpYXQiOjE3ODc5NTUwMDksImV4cCI6MTc4Nzk1NTkwOX0.mqdwZjiBSN4YMdm0QgvyISxNWKpnCzkGF96zZtqJVR0;