@baseUrl = http://localhost:3000/api

### Create Support Endpoint
POST {{baseUrl}}/support
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiI4NzE0MmM2NS0xM2Y3LTRlOWMtYjhiZC0yOTZkNjA1YjU0ZWQiLCJpYXQiOjE3ODg1NzE3NzEsImV4cCI6MTc4ODU3MjY3MX0.hHovXDkW4h-1a5HTj4zET3V6vO0OJNb7PmI2Yh5RU0k;refresh_token=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiI4NzE0MmM2NS0xM2Y3LTRlOWMtYjhiZC0yOTZkNjA1YjU0ZWQiLCJpYXQiOjE3ODg1NzE3NzEsImV4cCI6MTc4OTE3NjU3MX0.QuKCdD1l5M_94gTsy7SOGMuL_rMRaIpnGFTVt9BFJa4;

{
  "issue": "Product not working"
}

### Get support ticket
GET {{baseUrl}}/support/4c01f4db-14ad-42c2-9fc1-c79f371a6c0f
Cookie: access_token=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiI4NzE0MmM2NS0xM2Y3LTRlOWMtYjhiZC0yOTZkNjA1YjU0ZWQiLCJpYXQiOjE3ODg1NzE3NzEsImV4cCI6MTc4ODU3MjY3MX0.hHovXDkW4h-1a5HTj4zET3V6vO0OJNb7PmI2Yh5RU0k;refresh_token=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiI4NzE0MmM2NS0xM2Y3LTRlOWMtYjhiZC0yOTZkNjA1YjU0ZWQiLCJpYXQiOjE3ODg1NzE3NzEsImV4cCI6MTc4OTE3NjU3MX0.QuKCdD1l5M_94gTsy7SOGMuL_rMRaIpnGFTVt9BFJa4;
