@baseUrl = http://localhost:3000/api

GET {{baseUrl}}/users
Cookie: refresh_token=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiIyZjg1ZDI4MC01MjY0LTQ2ZDktOWI2ZS01MjY1YjY5NDY4ZjAiLCJpYXQiOjE3ODc5MDUyOTAsImV4cCI6MTc4ODUxMDA5MH0.Yg3wghhRLImaAQOsg_RD9rSCTSHQYB6XXuzh8n7hjYk;access_token=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiIyZjg1ZDI4MC01MjY0LTQ2ZDktOWI2ZS01MjY1YjY5NDY4ZjAiLCJpYXQiOjE3ODc5MDUyOTAsImV4cCI6MTc4NzkwNjE5MH0.Ju0dMqm9v1Noy0qZK96hN_Db8GClFhee9QMoHw14bNw;